[workspace]
resolver = "2"
members = [
    "base/*",
    "C_base/*",
    "core/*",
    "kernel",
    "kernel-bin",
    "Odin_base/odin-abi",
    "Odin_base/odin-abi-bridge",
    "Odin_base/odin-bin-loader", "inits",

    #"net/lib/net-types",
    #"net/lib/net-core",
    #"net/lib/net-buffer",
    #"net/lib/net-memory",
    #"net/lib/net-device",
    #"net/lib/net-driver",
    #"net/lib/net-packet",
    #"net/lib/net-ethernet",
    #"net/lib/net-arp",
    #"net/lib/net-ip",
    #"net/lib/net-ipv4",
    #"net/lib/net-ipv6",
    #"net/lib/net-icmp",
    #"net/lib/net-udp",
    #"net/lib/net-tcp",
    #"net/lib/net-dhcp",
    #"net/lib/net-dns",
    #"net/lib/net-routing",
    #"net/lib/net-interface",
    #"net/lib/net-socket",
    #"net/lib/net-loopback",
    #"net/lib/net-checksum",
    #"net/lib/net-queue",
    #"net/lib/net-config",
    #"net/lib/net-api",
    #"net/lib/net-stack",

    #"net/bin/net-test",
    #"net/bin/net-tool",
    #"net/bin/net-diagnostic",
    #"net/bin/net-loopback-test",
]

# `cargo run` at the workspace root should target the runnable kernel package.
default-members = ["kernel-bin"]

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = 2
# xc