[workspace]
resolver = "2"
members = [
    "base/*",
    "C_base/*",
    "core/*",
    "kernel",
    "kernel-bin",
    "Odin_base/odin-abi",
    "Odin_base/odin-abi-bridge",
    "Odin_base/odin-bin-loader",
]

# `cargo run` at the workspace root should target the runnable kernel package.
default-members = ["kernel-bin"]

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = 2
# xc